'use strict'

const SCORES = [
  { teamNumber: 1, match: 'Practice #1', score: 55, published: true },
  { teamNumber: 2, match: 'Practice #1', score: 426, published: true },
  { teamNumber: 8, match: 'Practice #1', score: 356, published: true },
  { teamNumber: 15, match: 'Practice #1', score: 240, published: true },
  { teamNumber: 54, match: 'Practice #1', score: 125, published: true },
  { teamNumber: 123, match: 'Practice #1', score: 256, published: true },
  { teamNumber: 132, match: 'Practice #1', score: 240, published: true },
  { teamNumber: 173, match: 'Practice #1', score: 523, published: true },
  { teamNumber: 182, match: 'Practice #1', score: 423, published: true },
  { teamNumber: 534, match: 'Practice #1', score: 465, published: true },
  { teamNumber: 856, match: 'Practice #1', score: 245, published: true },
  { teamNumber: 956, match: 'Practice #1', score: 156, published: true },
  { teamNumber: 981, match: 'Practice #1', score: 236, published: true },
  { teamNumber: 2212, match: 'Practice #1', score: 55, published: true },
  { teamNumber: 8846, match: 'Practice #1', score: 85, published: true },

  { teamNumber: 1, match: 'Qualifications #1', score: 50, published: true },
  { teamNumber: 2, match: 'Qualifications #1', score: 182, published: true },
  { teamNumber: 8, match: 'Qualifications #1', score: 165, published: true },
  { teamNumber: 15, match: 'Qualifications #1', score: 432, published: true },
  { teamNumber: 54, match: 'Qualifications #1', score: 162, published: true },
  { teamNumber: 123, match: 'Qualifications #1', score: 315, published: true },
  { teamNumber: 132, match: 'Qualifications #1', score: 152, published: true },
  { teamNumber: 173, match: 'Qualifications #1', score: 20, published: true },
  { teamNumber: 182, match: 'Qualifications #1', score: 24, published: true },
  { teamNumber: 534, match: 'Qualifications #1', score: 56, published: true },
  { teamNumber: 856, match: 'Qualifications #1', score: 75, published: true },
  { teamNumber: 956, match: 'Qualifications #1', score: 145, published: true },
  { teamNumber: 981, match: 'Qualifications #1', score: 245, published: true },
  { teamNumber: 2212, match: 'Qualifications #1', score: 345, published: true },
  { teamNumber: 8846, match: 'Qualifications #1', score: 465, published: true },

  { teamNumber: 1, match: 'Qualifications #2', score: 195, published: true },
  { teamNumber: 2, match: 'Qualifications #2', score: 375, published: true },
  { teamNumber: 8, match: 'Qualifications #2', score: 364, published: true },
  { teamNumber: 15, match: 'Qualifications #2', score: 195, published: true },
  { teamNumber: 54, match: 'Qualifications #2', score: 255, published: true },
  { teamNumber: 123, match: 'Qualifications #2', score: 153, published: true },
  { teamNumber: 132, match: 'Qualifications #2', score: 42, published: true },
  { teamNumber: 173, match: 'Qualifications #2', score: 245, published: true },
  { teamNumber: 182, match: 'Qualifications #2', score: 385, published: true },
  { teamNumber: 534, match: 'Qualifications #2', score: 45, published: true },
  { teamNumber: 856, match: 'Qualifications #2', score: 85, published: true },
  { teamNumber: 956, match: 'Qualifications #2', score: 235, published: true },
  { teamNumber: 981, match: 'Qualifications #2', score: 75, published: true },
  { teamNumber: 2212, match: 'Qualifications #2', score: 44, published: true },
  { teamNumber: 8846, match: 'Qualifications #2', score: 85, published: true },

  { teamNumber: 1, match: 'Qualifications #3', score: 125, published: true },
  { teamNumber: 2, match: 'Qualifications #3', score: 56, published: true },
  { teamNumber: 8, match: 'Qualifications #3', score: 455, published: true },
  { teamNumber: 15, match: 'Qualifications #3', score: 455, published: true },
  { teamNumber: 54, match: 'Qualifications #3', score: 35, published: true },
  { teamNumber: 123, match: 'Qualifications #3', score: 145, published: true },
  { teamNumber: 132, match: 'Qualifications #3', score: 255, published: true },
  { teamNumber: 173, match: 'Qualifications #3', score: 275, published: true },
  { teamNumber: 182, match: 'Qualifications #3', score: 135, published: true },
  { teamNumber: 534, match: 'Qualifications #3', score: 285, published: true },
  { teamNumber: 856, match: 'Qualifications #3', score: 95, published: true },
  { teamNumber: 956, match: 'Qualifications #3', score: 35, published: true },
  { teamNumber: 981, match: 'Qualifications #3', score: 45, published: true },
  { teamNumber: 2212, match: 'Qualifications #3', score: 250, published: true },
  { teamNumber: 8846, match: 'Qualifications #3', score: 350, published: true }
]

// eslint-disable-next-line node/exports-style
module.exports = SCORES
