'use strict'

const SCORES = [
  { teamNumber: 1, stage: 'Practice', round: 1, score: 55, published: true },
  { teamNumber: 2, stage: 'Practice', round: 1, score: 426, published: true },
  { teamNumber: 8, stage: 'Practice', round: 1, score: 356, published: true },
  { teamNumber: 15, stage: 'Practice', round: 1, score: 240, published: true },
  { teamNumber: 54, stage: 'Practice', round: 1, score: 125, published: true },
  { teamNumber: 123, stage: 'Practice', round: 1, score: 256, published: true },
  { teamNumber: 132, stage: 'Practice', round: 1, score: 240, published: true },
  { teamNumber: 173, stage: 'Practice', round: 1, score: 523, published: true },
  { teamNumber: 182, stage: 'Practice', round: 1, score: 423, published: true },
  { teamNumber: 534, stage: 'Practice', round: 1, score: 465, published: true },
  { teamNumber: 856, stage: 'Practice', round: 1, score: 245, published: true },
  { teamNumber: 956, stage: 'Practice', round: 1, score: 156, published: true },
  { teamNumber: 981, stage: 'Practice', round: 1, score: 236, published: true },
  { teamNumber: 2212, stage: 'Practice', round: 1, score: 55, published: true },
  { teamNumber: 8846, stage: 'Practice', round: 1, score: 85, published: true },

  { teamNumber: 1, stage: 'Qualifications', round: 1, score: 50, published: true },
  { teamNumber: 2, stage: 'Qualifications', round: 1, score: 182, published: true },
  { teamNumber: 8, stage: 'Qualifications', round: 1, score: 165, published: true },
  { teamNumber: 15, stage: 'Qualifications', round: 1, score: 432, published: true },
  { teamNumber: 54, stage: 'Qualifications', round: 1, score: 162, published: true },
  { teamNumber: 123, stage: 'Qualifications', round: 1, score: 315, published: true },
  { teamNumber: 132, stage: 'Qualifications', round: 1, score: 152, published: true },
  { teamNumber: 173, stage: 'Qualifications', round: 1, score: 20, published: true },
  { teamNumber: 182, stage: 'Qualifications', round: 1, score: 24, published: true },
  { teamNumber: 534, stage: 'Qualifications', round: 1, score: 56, published: true },
  { teamNumber: 856, stage: 'Qualifications', round: 1, score: 75, published: true },
  { teamNumber: 956, stage: 'Qualifications', round: 1, score: 145, published: true },
  { teamNumber: 981, stage: 'Qualifications', round: 1, noShow: true, published: true },
  { teamNumber: 2212, stage: 'Qualifications', round: 1, score: 345, published: true },
  { teamNumber: 8846, stage: 'Qualifications', round: 1, score: 465, published: true },

  { teamNumber: 1, stage: 'Qualifications', round: 2, score: 195, published: true },
  { teamNumber: 2, stage: 'Qualifications', round: 2, score: 375, published: true },
  { teamNumber: 8, stage: 'Qualifications', round: 2, score: 364, published: true },
  { teamNumber: 15, stage: 'Qualifications', round: 2, score: 195, published: true },
  { teamNumber: 54, stage: 'Qualifications', round: 2, score: 255, published: true },
  { teamNumber: 123, stage: 'Qualifications', round: 2, score: 153, published: true },
  { teamNumber: 132, stage: 'Qualifications', round: 2, score: 42, published: true },
  { teamNumber: 173, stage: 'Qualifications', round: 2, score: 245, published: true },
  { teamNumber: 182, stage: 'Qualifications', round: 2, score: 385, published: true },
  { teamNumber: 534, stage: 'Qualifications', round: 2, score: 45, published: true },
  { teamNumber: 856, stage: 'Qualifications', round: 2, score: 85, published: true },
  { teamNumber: 956, stage: 'Qualifications', round: 2, score: 235, published: true },
  { teamNumber: 981, stage: 'Qualifications', round: 2, noShow: true, published: true },
  { teamNumber: 2212, stage: 'Qualifications', round: 2, score: 44, published: true },
  { teamNumber: 8846, stage: 'Qualifications', round: 2, score: 85, published: true },

  { teamNumber: 1, stage: 'Qualifications', round: 3, score: 125, published: true },
  { teamNumber: 2, stage: 'Qualifications', round: 3, score: 56, published: true },
  { teamNumber: 8, stage: 'Qualifications', round: 3, score: 455, published: true },
  { teamNumber: 15, stage: 'Qualifications', round: 3, score: 455, published: true },
  { teamNumber: 54, stage: 'Qualifications', round: 3, score: 35, published: true },
  { teamNumber: 123, stage: 'Qualifications', round: 3, score: 145, published: true },
  { teamNumber: 132, stage: 'Qualifications', round: 3, score: 255, published: true },
  { teamNumber: 173, stage: 'Qualifications', round: 3, score: 275, published: true },
  { teamNumber: 182, stage: 'Qualifications', round: 3, score: 135, published: true },
  { teamNumber: 534, stage: 'Qualifications', round: 3, score: 285, published: true },
  { teamNumber: 856, stage: 'Qualifications', round: 3, score: 95, published: true },
  { teamNumber: 956, stage: 'Qualifications', round: 3, score: 35, published: true },
  { teamNumber: 981, stage: 'Qualifications', round: 3, noShow: true, published: true },
  { teamNumber: 2212, stage: 'Qualifications', round: 3, score: 250, published: true },
  { teamNumber: 8846, stage: 'Qualifications', round: 3, score: 350, published: true }
]

// eslint-disable-next-line node/exports-style
module.exports = SCORES
